version: '31'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fundamentals
    ports:
      - "5432:5432"
    command: -p 5432
    volumes:
       - ./data:/var/lib/postgresql/data.
